library:
  source-dirs: src
tests:
  day4-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day4
copyright: 2018 Author name here
maintainer: example@example.com
dependencies:
- base >= 4.7 && < 5
name: day4
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/day4
license: BSD3
executables:
  day4-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day4
    - parsec
    - containers
    - mtl
    - time >= 1.9.1
description: Please see the README on GitHub at <https://github.com/githubuser/day4#readme>
