library:
  source-dirs: src
tests:
  day3-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day3
copyright: 2018 Author name here
maintainer: example@example.com
dependencies:
- base >= 4.7 && < 5
name: day3
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/day3
license: BSD3
executables:
  day3-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtl
    - containers
    - vector
    - parsec
    - day3
description: Please see the README on GitHub at <https://github.com/githubuser/day3#readme>
