library:
  source-dirs: src
tests:
  day8-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day8
copyright: 2018 Author name here
maintainer: example@example.com
dependencies:
- base >= 4.7 && < 5
name: day8
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/day8
license: BSD3
executables:
  day8-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parsec
    - day8
description: Please see the README on GitHub at <https://github.com/githubuser/day8#readme>
